# Generated by Django 4.1.7 on 2023-03-15 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('co_autor', models.CharField(blank=True, max_length=30)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
                ('emprestado', models.BooleanField(default=False)),
                ('nome_emprestado', models.CharField(max_length=30)),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
            ],
        ),
    ]
